https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pynvml as pynvml
print(torch.__version__)

SCALAR

In [ ]:
scalar = torch.tensor(7)
scalar

In [ ]:
scalar.ndim

In [ ]:
#get tensor back as python int
scalar.item()

VECTOR

In [ ]:
vector = torch.tensor([7,7])
vector

In [ ]:
vector.ndim

In [ ]:
vector.shape


MATRIX


In [ ]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX.shape

TENSOR

In [ ]:

TENSOR = torch.tensor([[[ 
                        [1,2,3],
                        [4,5,6],
                        [7,8,9]
                      ],
                      [ 
                        [1,2,3],
                        [4,5,6],
                        [7,8,9]
                      ],
                      [ 
                        [1,2,3],
                        [4,5,6],
                        [7,8,9]
                      ]],
                      ])
TENSOR

In [ ]:
TENSOR.shape

In [ ]:
TENSOR.ndim

Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
#Create a random tensor of size (3, 4)
# import random
# random_tensor = torch.ones(size=(3,224,224))
# random_tensor[:, :, 1] = 0
# for i in range(224):
#     for j in range(224):
#         random_tensor[i,j,0] = random.randint(1,100)/100
#         random_tensor[i,j,1] = random.randint(1,100)/100
#         random_tensor[i,j,2] = random.randint(1,100)/100

# random_tensor

In [ ]:
# from torchvision.transforms import ToPILImage
# from IPython.display import Image
# a = ToPILImage(random_tensor)
# a = random_tensor.numpy()
# plt.imshow(a)

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

In [ ]:
zeros = torch.zeros(3,4)
zeros

In [ ]:
ones = torch.ones(3,4)
ones

In [ ]:
random_tensor[:,0] *= zeros[:,0]
random_tensor

Creating a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(1,11)
one_to_ten

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

Tensor datatypes are one of the 3 big errors you'll run into with pytorch and deep learning
1. Tensors are not the right datatype
2. Tensors are not the right shape
3. Tensors are not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype=None, 
                               device=None, 
                               requires_grad=False)
float_32_tensor


In [ ]:
float_32_tensor.dtype

In [ ]:
# float_16_tensor = torch.tensor([3.0,6.0,9.0], 
#                                dtype=torch.halfy, 
#                                device=None, 
#                                requires_grad=False)
# float_16_tensor

In [ ]:
# merged_tensor = float_32_tensor*float_16_tensor
# merged_tensor.dtype
# #keeps datatype of larger bit typey

In [ ]:
int_32_tensor = torch.tensor([3,6,8], dtype=torch.long)
int_32_tensor.shape

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

In [ ]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

In [ ]:
print(some_tensor.device)
some_tensor = some_tensor.to('cuda:0')
# some_tensor = some_tensor.cuda()
print(some_tensor.device)


Manipulating tensors (tensor operations)

*Addition
*Subtraction
*Multiplication (element-wise)
*Division
*Matrix multiplication


In [ ]:
#Create a tensor 
tensor = torch.tensor([1,2,3])
tensor

In [ ]:
#add 10
tensor + 10

In [ ]:
#Multiply tensor by 10
tensor*10

In [ ]:
#Subtract 10
tensor - 10

In [ ]:
#Divide by 10
tensor / 10

In [ ]:
torch.add(tensor,10)

In [ ]:
torch.mul(tensor,10)

In [ ]:
torch.subtract(tensor,10)

In [ ]:
torch.divide(tensor,10)

In [ ]:
tensor1 = torch.rand(3)*10
tensor1 = tensor1 // 1
tensor1

In [ ]:
tensor2 = torch.rand(3)*10
tensor2 = tensor2 // 1
tensor2


In [ ]:
tensor1*tensor2

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

In [ ]:
%%time
torch.matmul(tensor1,tensor2)

1. element-wise multiplication
2. matrix multiplication

there are two rules that performing matrix multiplication needs to satisfy:
1. the inner dimensions must match
(3,2) and (3,2) wont work
(2,3) and (3,2) will work

2. the resulting matrix has the shape of the outer dimensions
(2,3) and (3,2) -> (2,2)
(3,2) and (2,3) -> (3,3)

In [ ]:
#shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul

In [ ]:
tensor_A.shape, tensor_B.shape,'',tensor_A.shape, tensor_B.T.shape,'',torch.mm(tensor_A,tensor_B.T), torch.mm(tensor_A,tensor_B.T).shape


In [ ]:
tensor_A.shape, tensor_B.shape,'',tensor_A.T.shape, tensor_B.shape,'',torch.mm(tensor_A.T,tensor_B), torch.mm(tensor_A.T,tensor_B).shape

Finding the min,max,mean,sum (tensor aggregation)

In [ ]:
x = torch.arange(0,100,10)
x, x.dtype

In [ ]:
torch.min(x)

In [ ]:
torch.max(x)

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
torch.sum(x),x.sum()

In [ ]:
x

In [ ]:
x.argmax()

In [ ]:
x[x.argmax()]

In [ ]:
x.max()

reshaping, stacking, squeezing and unsqueezing tensors

1. Reshaping - reshapes an input tensor to a defined shape
2. View - return a view of an input tensor of a certain shape but keep the same memory as the original tensor
3. Stacking - combine multiple tensors on top of each other. Vertical (vstack) or side by side (hstack)
4. Squeeze - removes all `1` dimensions from a tensor
5. Unsqueeze - add a `1` dimension to a target tensor
6. Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

In [ ]:
#Change the view

In [ ]:
z = x.view(3,3)
z, z.shape

In [ ]:
z[:, 0] = 5
z, x

In [ ]:
#Stack tensors on top of each other
z = torch.rand(2,2)
z_stacked = torch.stack([z,z])
z, z_stacked

In [ ]:
x = torch.zeros(2,1,2)
x.shape, x

In [ ]:
z = x.squeeze()
z.shape, z

In [ ]:
x = torch.zeros(2,2)

In [ ]:
x.shape, x

In [ ]:
z = x.unsqueeze(dim=1)
z.shape,z

In [ ]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x = torch.randint(1,11,(2,2,3))
x.size(), x

In [ ]:
torch.permute(x, (0,2,1))


In [ ]:
x_original = torch.rand(size=(5, 5, 3)) # height, width, colour channels

x_permuted = x_original.permute(2,0,1)
x_permuted.shape

In [ ]:
x_original[1,1,0] = 5
x_original,x_original[1,1,0]


In [ ]:
x_permuted

In [ ]:
##INdexing (selecting data from tensors)



In [ ]:
#Create a tensor
x = torch.arange(1,10).reshape(1, 3, 3)
x, x.shape

In [ ]:
x[0]

In [ ]:
x[0][0]

In [ ]:
x[0][2][2]

In [ ]:
x[0,:,0]

In [ ]:
#get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

In [ ]:
#get all values of the 0 dimensions but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]

In [ ]:
#get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

In [ ]:
x[0,2,2]

In [ ]:
x[:,:,2]

In [ ]:
#NumPy array to tensor
import numpy as np

array = np.arange(1.0, 9.0)
tensor=torch.from_numpy(array).type(torch.float32)  #when converting from numpy to pytorch. pytorch reflects numpys default datatype which is float64 compared to pytorch (float32)
array,tensor
#changing numpy array doesnt mutate the tensor

In [ ]:
tensor

In [ ]:
#Tensor to numpy array
tensor = torch.ones(7)
# numpy_tensor = np.array(tensor)
numpy_tensor = tensor.numpy()

In [ ]:
numpy_tensor, numpy_tensor.dtype

#Reproducibility (trying to take random out of random)

How neural networks learn:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

Essentially what the random seed does is "flavour" the randomness

In [ ]:
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)
random_tensor_a == random_tensor_b

In [ ]:
#Lets make some random but reproducible tensors. set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)
random_tensor_c == random_tensor_d

## Running tensors and Pytorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA+NVIDIA hardware + PyTorch working behind the scenes

In [ ]:
!nvidia-smi

In [ ]:
torch.cuda.is_available()

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

In [ ]:
#Count number of devices
torch.cuda.device_count()

###3. putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
#Create a tensor (Default is on CPU)
tensor = torch.tensor([2,4,6])



#Tensor not on GPU
print(tensor, tensor.device)


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

In [ ]:
# Moving tensors back to CPU (for example for using NumPy)
tensor_on_gpu.numpy()

In [ ]:
#To fix the GPU tensor with NumPy issue. we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

00. PyTorch Fundamentals Exercises

1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

- The documentation on torch.Tensor.
- The documentation on torch.cuda.

2. Create a random tensor with shape (7, 7).

In [ ]:
import torch

In [ ]:
rand_tensor = torch.rand(7,7)
rand_tensor

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
rand_tensor_2 = torch.rand(1,7)
rand_tensor_2

In [ ]:
rand1_mul_rand2 = rand_tensor @ rand_tensor_2.T
rand1_mul_rand2

4. Set the random seed to 0 and do 2 & 3 over again.
The output should be:

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))

In [272]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

rand_tensor_1 = torch.rand(7,7)
rand_tensor_2 = torch.rand(1,7)
rand1_mul_rand2 = rand_tensor_1 @ rand_tensor_2.T
rand1_mul_rand2

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
If there is, set the GPU random seed to 1234.

In [352]:
CUDA_SEED = 1234
torch.cuda.manual_seed_all(CUDA_SEED)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:\
Device: cuda\
(tensor([[0.0290, 0.4019, 0.2598],\
        [0.3666, 0.0583, 0.7006]], device='cuda:0'),\
tensor([[0.0518, 0.4681, 0.6738],\
        [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [362]:
torch.manual_seed(CUDA_SEED)

gpu_tensor_1 = torch.rand(2,3).to('cuda')
gpu_tensor_2 = torch.rand(2,3).to('cuda')
gpu_tensor_1, gpu_tensor_2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).\
The output should look like:\

(tensor([[0.3647, 0.4709],\
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

In [363]:
matmul_gpu_tensors = gpu_tensor_1 @ gpu_tensor_2.T
matmul_gpu_tensors

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

8. Find the maximum and minimum values of the output of 7.

In [367]:
matmul_gpu_tensors.max(),matmul_gpu_tensors.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

9. Find the maximum and minimum index values of the output of 7.

In [368]:
matmul_gpu_tensors.argmax(), matmul_gpu_tensors.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.\
The output should look like:\

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,\
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])\
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,\
        0.8513]) torch.Size([10])

In [371]:
torch.manual_seed(7)
tensor = torch.rand(1,1,1,10)
new_tensor = tensor.squeeze()

print(tensor,tensor.shape)
print(new_tensor, new_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
